title: CTF Writeups
description: My personal writeups for CTF
encoding: UTF-8
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

# needed for jekyll-sitemap generator
url: "https://github.com/Noman-Aziz/ctf-writeups" 

# logo
avatar: /assets/images/jekyll-logo.svg 

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor

